# Generated by Django 3.2.3 on 2021-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('liveTime', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('memberDiff', models.CharField(max_length=200, null=True)),
                ('chat', models.CharField(max_length=500, null=True)),
                ('userCode', models.IntegerField(null=True)),
                ('userGroup', models.IntegerField(null=True)),
                ('userId', models.CharField(max_length=200, null=True)),
                ('userName', models.CharField(max_length=200, null=True)),
                ('userNick', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
