# Generated by Django 3.2.6 on 2021-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200, null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
    ]
